# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 376f4531ab3182568ca956c51391f490ef8e271192b6ec99319f6bea7a1a5eb00569120a0ff0d4bc2d5e5be10429f9e6615200b94a3915f6e2d710dcafbe0068

test:
  secret_key_base: 05235e28b0753b62c2e4f5aafe9bb5dca969b191b39241b00da8a829f8b11ea7d973dd848de2dc41556f8805f83b0d26557c007e4237969248d47ebea119e5b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
